services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx-container
    ports:
      - "80:80"
    volumes:
      - ./app:/var/www/pet-project
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - network
  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: php81-container
    ports:
      - "9000:9000"
    volumes:
      - ./app:/var/www/pet-project
    networks:
      - network
networks:
  network: